version: '3'

services:
  db:
    image: mysql:8.0.28
    restart: always
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=snippetbox
    - MYSQL_USER=dev
    - MYSQL_PASSWORD=dev
    volumes:
    - ./sql:/docker-entrypoint-initdb.d
