name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      testdb:
        image: mysql:8.0.28
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: snippetbox
          MYSQL_USER: test
          MYSQL_PASSWORD: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: make test

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          args: --timeout=10m
